name: 'OWASP ZAP Report Generate'
description: 'Convert owasp zap report into issues in Github Repository'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  generate_report_dir:
    description: 'The Path contain reports'
    required: true
    default: ${{ github.workspace }}
  token:
    description: 'GitHub Token to create issues in the repository'
    required: false
    default: ${{ github.token }}
  issue_title:
    description: 'The title for the GitHub issue to be created'
    required: false
    default: 'ZAP Full Scan Report'
runs:
  using: 'node12'
  main: 'dist/index.js'
